title: Zainab Iftikhar
tagline: Ph.D. Candidate in CS at Brown
url: http://zainabiftikhar.com
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

github:
  repo: https://zainabiftikhar/zainabiftikhar.github.io
  
nav:
 #- name: "about"
 #  link: "/"
 - name: "Projects"
   link: "/projects"
 - name: "Blog"
   link: "/blog"
 - name: "CV"
   link: "/assets/cv.pdf"
 - name: "GScholar"
   link: "https://scholar.google.com/citations?hl=en&user=x9GuCAQAAAAJ"
